### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by oOHenry** [lukasmalkmus/tankerkoenig_exporter#1]
* https://quay.io/repository/lukasmalkmus/tankerkoenig-exporter says: "Repository not found"

**Comment by lukasmalkmus** [comment]
Jup, something was missing there. I pushed the images to [dockerhub](https://hub.docker.com/r/lukasmalkmus/tankerkoenig-exporter/) and dropped quay. Feel free to reopen this issues if you need something else.

**Comment by oOHenry** [comment]
Hi, thanks for the quick reply the pull works now. But I can't use the image on my server because it has a binary for MacOS in it, do you have a docker image for linux amd_64 as well?

**Comment by lukasmalkmus** [comment]
Ups, small mistake on my side 🤦‍♂️ I pushed the rebuild images with the correct binary.
