### ISSUE TITLE
Docker Image Compatibility Issue on arm64 Architecture

### ISSUE THREAD

**Issue by ffidan61** [lukasmalkmus/tankerkoenig_exporter#17]
I'm encountering an issue when attempting to run the tankerkoenig-exporter Docker image on an arm64 architecture. The error message I'm receiving is as follows:
```
Attaching to tankerkoenig-exporter
tankerkoenig-exporter | exec /usr/bin/tankerkoenig_exporter: exec format error
tankerkoenig-exporter exited with code 1
``` 

### Steps to Reproduce:
1. Use a host with an arm64 architecture.
2. Pull and run the tankerkoenig-exporter Docker image.

### Expected Behavior:
The tankerkoenig-exporter Docker image should run successfully on arm64 architecture without any errors.

### Actual Behavior:
The Docker image fails to execute on the arm64 architecture, producing the "exec format error" and exiting with code 1.

Additional Information:
I noticed that the Docker image may only be available for amd64 architecture. Could you please confirm if this is the case? If so, are there any plans to provide support for arm64 architecture in the future?

Thank you for your time

**Comment by lukasmalkmus** [comment]
@ffidan61 Sorry I couldn't follow up with this in time. I see you closed it as "completed" right on the day of creation. Did you sort out your problem?

**Comment by ffidan61** [comment]
@lukasmalkmus No need to be sorry. 

Yes I could resolve my issue right after creating the issue.

Thanks for your time
