### ISSUE TITLE
Cant see any station related information (docker image 0.7.0)

### ISSUE THREAD

**Issue by fl0wx** [lukasmalkmus/tankerkoenig_exporter#2]
Hey ho,

i just tried you docker image and something seems to be wrong. maybe i have done a mistake. Could you please help me?

my command:
`docker run -p 9386:9386 -d --name=tk-exporter --restart=unless-stopped -e --env-file=/volume1/homes/docker/tankerkoenig/.env lukasmalkmus/tankerkoenig-exporter:latest --api.stations="51d4b715-a095-1aa0-e100-80009459e03a,3c892986-fd11-497c-a2ca-a09494abe761,5cb08765-da25-4bee-a118-a5710cb9aae5,fd606c1d-2f43-47df-8934-d1ea98871767"`

I dont see any gasstation informations. Just tk_up = 1, tk_exporter_scrapes_total = 3, ...failures=0, etc. But no station related informations. I checked also the /metrics page.

What am i missing?

**Comment by lukasmalkmus** [comment]
Hi, sorry for taking so long to respond. I was super busy... I noticed that running the systemd-service produces no metrics. Running the binary manually, with the same parameters works flawlessly. Guess it is the same with docker.

But I wasn't able to isolate the problem. If you are still interested: Could you try running the binary manually with the same parameters and check if you get metrics?

**Comment by lukasmalkmus** [comment]
I'm closing this issue as it is stale. Also the exporter got a small overhaul.
