### ISSUE TITLE
Can't create Tankerkoenig exporter

### ISSUE THREAD

**Issue by idolux** [lukasmalkmus/tankerkoenig_exporter#5]
The exporter is not working anymore

I tested the command from the README:

```
$ docker run -p9386:9386/tcp --env-file=.env lukasmalkmus/tankerkoenig-exporter:v0.9.1 --api.stations="51d4b55e-a095-1aa0-e100-80009459e03a"
level=info ts=2021-02-21T21:52:48.986Z caller=tankerkoenig_exporter.go:256 msg="Starting tankerkoenig_exporter" version="(version=0.9.1, branch=master, revision=5421528dfdbf9997282db88aeede5ccce097c37f)"
level=info ts=2021-02-21T21:52:48.986Z caller=tankerkoenig_exporter.go:257 msg="Build context" context="(go=go1.13.15, user=root@fc960557aac2, date=20201214-00:42:10)"
level=error ts=2021-02-21T21:52:49.157Z caller=tankerkoenig_exporter.go:269 msg="Can't create Tankerkoenig exporter" err="station \"51d4b55e-a095-1aa0-e100-80009459e03a\" was not found"
```

**Comment by idolux** [comment]
@lukasmalkmus are you around? not sure why it fails

**Comment by lukasmalkmus** [comment]
Will look into this if I have some time on the weekend 👍

**Comment by lukasmalkmus** [comment]
But maybe the station from the README doesn't exist anymore. Follow the rest of the README and find some valid station IDs  for some stations of your choice. Also make sure the .env file contains the `TANKERKOENIG_API_KEY="YOUR_API_TOKEN"` token and add your TankerKoenig token.

**Comment by idolux** [comment]
I doubled checked and tested the API in my browser. Apparently it is impossible to enable my API key. I found some other key online and it works just fine. Going to check with tankerkoenig what's up with my key.

Sorry to bother you.

**Comment by idolux** [comment]
Would still be nice to throw a proper error if the API key is wrong ;)

**Comment by lukasmalkmus** [comment]
I will investigate. Usually, the API should throw 401/403, rather than 404.

**Comment by idolux** [comment]
It's actually a 200 all the time

https://creativecommons.tankerkoenig.de/json/prices.php?ids=4429a7d9-fb2d-4c29-8cfe-2ca90323f9f8&apikey=00000000-0000-0000-0000-000000000001
https://creativecommons.tankerkoenig.de/json/prices.php?ids=4429a7d9-fb2d-4c29-8cfe-2ca90323f9f8&apikey=asdf
